# Generated by Django 2.1.4 on 2019-01-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OvKv6',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('receive', models.DateTimeField()),
                ('message', models.DateTimeField()),
                ('vehicle', models.DateTimeField()),
                ('messagetype', models.CharField(max_length=255)),
                ('operatingday', models.DateField()),
                ('dataownercode', models.CharField(max_length=255)),
                ('lineplanningnumber', models.CharField(max_length=255)),
                ('reinforcementnumber', models.SmallIntegerField()),
                ('userstopcode', models.CharField(max_length=255)),
                ('passagesequencenumber', models.SmallIntegerField()),
                ('distancesincelastuserstop', models.IntegerField()),
                ('punctuality', models.IntegerField()),
                ('rd_x', models.IntegerField()),
                ('rd_y', models.IntegerField()),
                ('blockcode', models.IntegerField()),
                ('vehiclenumber', models.IntegerField()),
                ('wheelchairaccessible', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('trip_hash', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OvRaw',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('feed', models.CharField(max_length=255)),
                ('xml', models.BinaryField()),
            ],
        ),
    ]
