# Generated by Django 2.1.5 on 2019-01-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ov', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovkv6',
            name='blockcode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ovkv6',
            name='distancesincelastuserstop',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ovkv6',
            name='operatingday',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='ovkv6',
            name='passagesequencenumber',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ovkv6',
            name='punctuality',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ovkv6',
            name='rd_x',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ovkv6',
            name='rd_y',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ovkv6',
            name='reinforcementnumber',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ovkv6',
            name='trip_hash',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ovkv6',
            name='vehiclenumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ovkv6',
            name='wheelchairaccessible',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
