# Generated by Django 2.1.5 on 2019-01-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ov', '0005_ovstop'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvRoutes',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('route_id', models.IntegerField()),
                ('service_id', models.IntegerField()),
                ('trip_id', models.IntegerField()),
                ('headsign', models.CharField(max_length=255, null=True)),
                ('short_name', models.CharField(max_length=255, null=True)),
                ('long_name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ovkv6',
            name='journeynumber',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
