# Generated by Django 2.1.7 on 2019-03-20 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ov', '0007_add_kv6_table_partitioning'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvRouteSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(db_index=True, max_length=255)),
                ('stop_code', models.CharField(db_index=True, max_length=255)),
                ('stop_sequence', models.IntegerField()),
                ('shape_dist_traveled', models.IntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ov.OvRoutes')),
            ],
        ),
        migrations.AddField(
            model_name='ovstop',
            name='stop_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ovkv6',
            name='avg_speed',
            field=models.FloatField(null=True),
        ),        
    ]
