# Generated by Django 2.1.7 on 2019-04-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ov', '0008_auto_20190320_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ovkv6',
            name='avg_speed',
        ),
        migrations.AddField(
            model_name='ovkv6',
            name='distance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ovkv6',
            name='time',
            field=models.IntegerField(null=True),
        ),
    ]
