# Generated by Django 2.1.7 on 2019-04-16 07:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ov', '0009_auto_20190401_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='ovkv6',
            name='prev_geo_location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=28992),
        ),
        migrations.AddField(
            model_name='ovkv6',
            name='prev_userstopcode',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
