# Generated by Django 2.2.2 on 2019-09-16 14:32

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuidanceSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=255, unique=True)),
                ('geometrie', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=10)),
                ('pub_date', models.DateTimeField()),
                ('removed', models.NullBooleanField()),
                ('stadsdeel', models.CharField(max_length=1, null=True)),
                ('buurt_code', models.CharField(max_length=10, null=True)),
                ('scraped_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'importer_guidancesign',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='GuidanceSignSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'guidancesign_raw',
                'ordering': ('scraped_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ParkingLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('geometrie', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('state', models.CharField(max_length=10)),
                ('free_space_short', models.IntegerField(blank=True, default=None, help_text='Short duration parking availability', null=True)),
                ('free_space_long', models.IntegerField(blank=True, default=None, help_text='Long duration parking availability', null=True)),
                ('short_capacity', models.IntegerField(blank=True, default=None, help_text='Short duration parking capacity', null=True)),
                ('long_capacity', models.IntegerField(blank=True, default=None, help_text='Long duration parking capacity', null=True)),
                ('pub_date', models.DateTimeField()),
                ('stadsdeel', models.CharField(max_length=1, null=True)),
                ('buurt_code', models.CharField(max_length=10, null=True)),
                ('scraped_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'importer_parkinglocation',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='ParkingLocationSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'parkinglocation_raw',
                'ordering': ('scraped_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ParkingGuidanceDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('output', models.CharField(blank=True, max_length=100)),
                ('output_description', models.CharField(blank=True, max_length=255)),
                ('scraped_at', models.DateTimeField()),
                ('guidance_sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='displays', to='parkeergarages.GuidanceSign', to_field='api_id')),
            ],
            options={
                'db_table': 'importer_parkingguidancedisplay',
                'ordering': ('-pub_date',),
            },
        ),
    ]
