# Generated by Django 2.2.2 on 2019-08-06 07:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat_tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoatTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmsi', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('type', models.IntegerField(null=True)),
                ('length', models.IntegerField(null=True)),
                ('width', models.IntegerField(null=True)),
                ('geo_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('speed', models.IntegerField()),
                ('direction', models.IntegerField()),
                ('status', models.IntegerField()),
                ('sensor', models.CharField(max_length=255)),
                ('lastupdate', models.DateTimeField()),
                ('lastmoved', models.DateTimeField(null=True)),
                ('scraped_at', models.DateTimeField()),
            ],
            options={
                'ordering': ('scraped_at',),
            },
        ),
    ]
