# Generated by Django 2.2.2 on 2019-08-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat_tracking', '0002_boattracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boattracking',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
