# Generated by Django 2.2.2 on 2019-09-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat_tracking', '0003_auto_20190807_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boattracking',
            name='lastmoved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boattracking',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boattracking',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='boattracking',
            name='type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boattracking',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
