# Generated by Django 2.2.2 on 2019-09-18 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boat_tracking', '0004_auto_20190918_1555'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='boattrackingraw',
            table='boat_tracking_boattrackingraw',
        ),
    ]
