# Generated by Django 2.2.2 on 2019-09-19 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boat_tracking', '0005_auto_20190918_1620'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoatTrackingRaw',
            new_name='BoatTrackingSnapshot',
        ),
    ]
