# Generated by Django 2.1.4 on 2019-01-21 10:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdpartyTravelTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_site_reference', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=2)),
                ('length', models.IntegerField()),
                ('geometrie', django.contrib.gis.db.models.fields.LineStringField(null=True, srid=4326)),
                ('timestamp', models.DateTimeField()),
                ('scraped_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'importer_thirdparty_traveltime',
                'ordering': ('-scraped_at',),
            },
        ),
        migrations.CreateModel(
            name='TravelTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_site_reference', models.CharField(max_length=255)),
                ('computational_method', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_incomplete_input', models.IntegerField()),
                ('number_of_input_values_used', models.IntegerField()),
                ('standard_deviation', models.FloatField()),
                ('supplier_calculated_data_quality', models.FloatField()),
                ('duration', models.FloatField()),
                ('data_error', models.NullBooleanField()),
                ('measurement_time', models.DateTimeField()),
                ('scraped_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'importer_traveltime',
                'ordering': ('-scraped_at',),
            },
        ),
    ]
