# Generated by Django 2.1.5 on 2019-01-29 15:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_site_reference', models.CharField(max_length=255)),
                ('computational_method', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_incomplete_input', models.IntegerField()),
                ('number_of_input_values_used', models.IntegerField()),
                ('standard_deviation', models.FloatField()),
                ('supplier_calculated_data_quality', models.FloatField()),
                ('duration', models.FloatField()),
                ('data_error', models.NullBooleanField()),
                ('measurement_time', models.DateTimeField()),
                ('scraped_at', models.DateTimeField()),
                ('geometrie', django.contrib.gis.db.models.fields.LineStringField(null=True, srid=4326)),
                ('stadsdeel', models.CharField(max_length=1)),
                ('buurt_code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'importer_traveltime',
                'ordering': ('-scraped_at',),
                'managed': settings.TESTING,
            },
        ),
    ]
