# Generated by Django 2.1.5 on 2019-01-29 13:39

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('ndw', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThirdpartyTravelTime',
        ),
        migrations.AlterModelOptions(
            name='traveltime',
            options={'managed': settings.TESTING, 'ordering': ('-scraped_at',)},
        ),
    ]
