# Generated by Django 2.1.4 on 2018-12-10 14:38

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OvFiets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('station_code', models.CharField(max_length=4, null=True)),
                ('location_code', models.CharField(max_length=7)),
                ('open', models.CharField(max_length=7)),
                ('geometrie', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('rental_bikes', models.IntegerField()),
                ('fetch_time', models.DateTimeField()),
                ('scraped_at', models.DateTimeField()),
                ('stadsdeel', models.CharField(max_length=1)),
                ('opening_hours', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('unmapped', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
            options={
                'db_table': 'importer_ovfiets',
                'ordering': ('location_code', 'id'),
                'managed': settings.TESTING,
            },
        ),
    ]
