# Generated by Django 2.2.2 on 2019-08-21 13:16

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OvFiets',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(null=True)),
                ('station_code', models.CharField(max_length=4, null=True)),
                ('location_code', models.CharField(max_length=7)),
                ('open', models.CharField(max_length=7)),
                ('geometrie', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('rental_bikes', models.IntegerField(null=True)),
                ('fetch_time', models.DateTimeField(db_index=True)),
                ('scraped_at', models.DateTimeField(db_index=True)),
                ('stadsdeel', models.CharField(max_length=4, null=True)),
                ('buurt_code', models.CharField(max_length=5, null=True)),
                ('opening_hours', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('unmapped', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
            options={
                'db_table': 'importer_ovfiets',
                'ordering': ('location_code', 'id'),
            },
        ),
        migrations.CreateModel(
            name='OvFietsRaw',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'ovfiets_raw',
                'ordering': ('scraped_at', 'id'),
            },
        ),
    ]
