# Generated by Django 2.2.2 on 2019-09-19 14:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovfiets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OvFietsRaw',
            new_name='OvFietsSnapshot',
        ),
        migrations.AlterField(
            model_name='ovfiets',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ovfiets',
            name='location_code',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='ovfiets',
            name='opening_hours',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ovfiets',
            name='rental_bikes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ovfiets',
            name='station_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='ovfiets',
            name='unmapped',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
